# Generated by Django 3.2.8 on 2021-10-12 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_alter_link_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ('price_difference', '-created')},
        ),
    ]
